### ISSUE TITLE
Mn wallet crashes if reindexed for txindex=1 

### ISSUE THREAD

**Issue by GilAlexander** [spreadcoin-project/spreadcoin#15]
Current masternode win64 wallet version v0.9.15.4-g3d5c6b6-beta crashes on start if blocks were reindexed after txindex=1 in spreadcoin.conf.

How to reproduct:
1) Run wallet, wait for syncronization, exit.
2) Add txindex=1 to \Roaming\SpreadTestCoin\spreadcoin.conf
3) Run wallet, confirm for "You need to rebuild ..."
4) Wait for rebuild.
5) Exit and start again.

Will show:
"MinGW Euntime Assertion
Assertion failed!
Program: ..
File: src/masternodes_elected.cpp, Line 103
Expression: masternodes.erase(outpoint) != 0"

**Comment by Mr-Spread** [comment]
Fixed https://github.com/spreadcoin-project/spreadcoin/commit/59dd83a782dbadf79a8b5332945700f86eb5e1cd
